name: Deploy to Cloud Run

on:
  push:
    branches:
      - main
      - develop

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: ${{ secrets.GCP_REGION }}
  GAR_LOCATION: ${{ secrets.GAR_LOCATION }}
  SERVICE_NAME: ${{ secrets.SERVICE_NAME }}
  IMAGE: ${{ secrets.GAR_LOCATION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/etihad-repo/etihad-poc

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      # 1. Checkout code
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Authenticate with GCP
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v3
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      # 3. Setup gcloud
      - name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}

      # 4. Configure Docker for Artifact Registry
      - name: Configure Docker
        run: |
          gcloud auth configure-docker $GAR_LOCATION-docker.pkg.dev

      # 5. Build Docker image
      - name: Build Image
        run: |
          docker build -t $IMAGE:${{ github.sha }} ./backend

      # 6. Push Image
      - name: Push Image
        run: |
          docker push $IMAGE:${{ github.sha }}

      # 7. Deploy to Cloud Run
      - name: Deploy
        uses: google-github-actions/deploy-cloudrun@v3
        with:
          service: ${{ env.SERVICE_NAME }}
          region: ${{ env.REGION }}
          image: ${{ env.IMAGE }}:${{ github.sha }}

      # 8. Output URL
      - name: Show URL
        run: echo "Service deployed successfully 🚀"
